M48
; DRILL file {KiCad 9.0.4} date 2026-02-12T22:59:18+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-12T22:59:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0425
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1280
%
G90
G05
T1
X5.6439Y-4.8133
X5.9891Y-4.8133
T2
X5.6439Y-4.4983
X5.9891Y-4.4983
T3
X5.2507Y-2.0397
X5.2507Y-5.583
T4
X5.9661Y-5.1139
X5.9661Y-5.5639
M30
